### ISSUE TITLE
## Feature requests and todos

### ISSUE THREAD

**Issue by mcguirepr89** [mcguirepr89/BirdNET-Pi#127]
## Feature requests and todos
I'm trying to keep the feature requests in one place so that I don't lose track of them. If you don't see your previously mentioned feature request below, please comment and let me know so that I will add it and it will not be forgotten nor overlooked -- thank you

- [ ] Link recordings and spectrograms to database view #125 
- [ ] API access to database and data #125 
- [ ] Offload to USB -- possibly already remedied by having the File Manager? Still no USB to test with :neutral_face: #57 
- [ ] DropIns directory for adding recordings to analysis service #118 
- [ ] _Urban_, _Suburban_, and _Field (Research)_ options #115 
- [ ] Automatic/Dynamic `include_species_list.txt` by region -- possible utilizing eBird grid data https://github.com/mcguirepr89/BirdNET-Pi/discussions/125#discussioncomment-2112105
- [ ] New documentation for most things 
- [ ] New `mobile.html` 
- [ ] Add translations for web pages and tool to switch to them 
- [ ] Indicate false positive detections in database #125 
- [ ] Easy navigation to historical chart data (`URL/Charts` for now) #125 
- [x] 1 extraction per detection (keep highest confidence score) #106 
- [x] Have `daily_plot.py` read from database (scheduled for this weekend)
- [x] `analyze.py` read from stream / prevent model rebuilding in `analyze.py` **on its way https://github.com/mcguirepr89/BirdNET-Pi/discussions/125#discussioncomment-2111644**
- [x] BirdWeather ID request form email template @timsterc
- [x] Build out `first_boot.html`

_Originally posted by @mcguirepr89 in https://github.com/mcguirepr89/BirdNET-Pi/discussions/125#discussioncomment-2090498_
